#!/usr/bin/env python3

from SCons.Script import Environment, Glob, ARGUMENTS, Command, Default, Exit
import os

PROJECT_NAME = "godot_apng"

GODOT_CPP = "godot-cpp"
SOURCE_DIR = "src"



OUTPUT_DIR = "project/addons/GodotAnimatedPNGParser"
GDEXTENSION_FILE = os.path.join(
    OUTPUT_DIR,
    "GodotAPNGParser.gdextension"
)

OUTPUT_ENGINE_DIR = "/addons/GodotAnimatedPNGParser"


ENTRY_SYMBOL = "godot_apng_library_init"

platform = ARGUMENTS.get("platform", "linux")
arch = ARGUMENTS.get("arch", "x86_64")
target = ARGUMENTS.get("target", "template_debug")

if platform not in ["linux", "windows"]:
    print("Unsupported platform: " + platform)
    Exit(1)


# 
# Environment
# 

env = SConscript("godot-cpp/SConstruct")

# Windows cross compiler
if platform == "windows":
    env["CC"] = "x86_64-w64-mingw32-gcc"
    env["CXX"] = "x86_64-w64-mingw32-g++"
    env["AR"] = "x86_64-w64-mingw32-ar"
    env["RANLIB"] = "x86_64-w64-mingw32-ranlib"


env.Append(CPPPATH=[
    GODOT_CPP + "/include",
    GODOT_CPP + "/gen/include",
    GODOT_CPP + "/gdextension"
])

# 
# Sources
# 

sources = Glob(
    SOURCE_DIR + "/*.cpp"
)

#
# Documentation
#

if target in ["editor", "template_debug"]:
    doc_data = env.GodotCPPDocData("src/gen/doc_data.gen.cpp", source=Glob("doc_classes/*.xml"))
    sources.append(doc_data)


# 
# Find godot-cpp
# 

godot_cpp_bin = GODOT_CPP + "/bin"

if not os.path.isdir(godot_cpp_bin):
    print("ERROR: Missing godot-cpp/bin")
    Exit(1)

godot_cpp_lib = None

expected_name = (
    "libgodot-cpp."
    + platform
    + "."
    + target
    + "."
    + arch
    + ".a"
)

expected_path = os.path.join(
    godot_cpp_bin,
    expected_name
)

if os.path.isfile(expected_path):
    godot_cpp_lib = expected_path

if godot_cpp_lib is None:
    print("ERROR: Could not find:")
    print("  " + expected_path)
    print()
    print("Available libraries:")

    for filename in os.listdir(godot_cpp_bin):
        if filename.endswith(".a"):
            print("  " + filename)

    Exit(1)

print("Using godot-cpp:")
print("  " + godot_cpp_lib)


# 
# Link godot-cpp
# 

# Link godot-cpp
env.Append(
    LINKFLAGS=[
        "-Wl,--whole-archive",
        godot_cpp_lib,
        "-Wl,--no-whole-archive"
    ]
)


# 
# Output
# 

if platform == "linux":

    output_name = (
        "GodotAPNGParser.linux.x86_64."+target+".so"
    )

elif platform == "windows":

    output_name = (
        "GodotAPNGParser.windows.x86_64."+target+".dll"
    )

target_library = os.path.join(
    OUTPUT_DIR,
    output_name
)


# 
# Build extension
# 

library = env.SharedLibrary(
    target=target_library,
    source=sources
)
